[package]
name = "libpmu"
version = "0.1.0"
edition = "2021"

[[example]]
name = "simple_stat"
path = "example/simple_stat.rs"

[[example]]
name = "list_events"
path = "example/list_events.rs"

[dependencies]
cfg-if = "1.0.0"
dlopen2 = "0.4.1"
libc = "0.2.144"
perf-event-open-sys2 = "5.0.3"
